# Generated by Django 6.0.6 on 2026-07-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sena', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.IntegerField()),
                ('categoria', models.CharField(choices=[('Herramientas', 'Herramientas'), ('Fijacion', 'Fijación & Textura'), ('Cuidado', 'Cuidado Capilar'), ('Barba', 'Barba & Afeitado')], default='Herramientas', max_length=20)),
                ('imagen_url', models.URLField(blank=True, max_length=500)),
                ('stock', models.IntegerField(default=0)),
                ('disponible', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
