# Generated by Django 6.0.6 on 2026-07-30 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sena', '0002_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen_url',
        ),
    ]
