# Generated by Django 6.0.6 on 2026-07-31 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sena', '0003_remove_producto_imagen_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20),
        ),
    ]
