# Generated by Django 6.1 on 2026-08-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sena', '0007_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Admin', 'ADMINISTRADOR'), ('Barbero', 'BARBERO'), ('Cliente', 'CLIENTE')], default='Cliente', max_length=15),
        ),
    ]
