# Generated by Django 6.1 on 2026-08-15 00:00

from django.db import migrations


def actualizar_roles(apps, schema_editor):
    Usuario = apps.get_model('sena', 'Usuario')
    RegistroIngreso = apps.get_model('sena', 'RegistroIngreso')
    
    # Actualizar usuarios con rol "Peluquero" a "Barbero"
    Usuario.objects.filter(rol="Peluquero").update(rol="Barbero")
    
    # Actualizar registros de ingreso
    RegistroIngreso.objects.filter(rol="Peluquero").update(rol="Barbero")


def revertir_roles(apps, schema_editor):
    Usuario = apps.get_model('sena', 'Usuario')
    RegistroIngreso = apps.get_model('sena', 'RegistroIngreso')
    
    Usuario.objects.filter(rol="Barbero").update(rol="Peluquero")
    RegistroIngreso.objects.filter(rol="Barbero").update(rol="Peluquero")


class Migration(migrations.Migration):

    dependencies = [
        ('sena', '0008_cambiar_peluquero_a_barbero'),
    ]

    operations = [
        migrations.RunPython(actualizar_roles, revertir_roles),
    ]
