# Generated by Django 6.1 on 2026-08-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sena', '0012_reserva_completada'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.URLField(blank=True, default=''),
        ),
    ]
