# Generated by Django 6.1 on 2026-08-20 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sena', '0014_usuario_activo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horariotrabajo',
            options={'ordering': ['dia_semana']},
        ),
        migrations.AddField(
            model_name='horariotrabajo',
            name='peluqueria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='sena.peluqueria'),
        ),
        migrations.AlterField(
            model_name='horariotrabajo',
            name='dia_semana',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')]),
        ),
        migrations.AlterUniqueTogether(
            name='horariotrabajo',
            unique_together={('peluqueria', 'dia_semana')},
        ),
    ]
