# Generated by Django 6.1 on 2026-08-20 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sena', '0015_alter_horariotrabajo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloqueohorario',
            name='peluqueria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='sena.peluqueria'),
        ),
    ]
