# Generated by Django 6.1 on 2026-08-20 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sena', '0013_producto_imagen'),
        ('sena', '0016_bloqueohorario_peluqueria'),
    ]

    operations = [
    ]
