# Generated by Django 6.1 on 2026-09-10 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sena', '0020_alter_usuario_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='peluqueria',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='peluqueria',
            name='dueno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peluquerias_dueno', to='sena.usuario'),
        ),
        migrations.AddField(
            model_name='peluqueria',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='peluquerias/'),
        ),
        migrations.CreateModel(
            name='ImagenPeluqueria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='galeria/')),
                ('descripcion', models.CharField(blank=True, default='', max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('peluqueria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='sena.peluqueria')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
