# Generated by Django 6.1 on 2026-09-21 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sena', '0021_agregar_peluqueria_dueno_galeria'),
        ('sena', '0021_usuario_foto_usuario_peluqueria'),
    ]

    operations = [
    ]
